sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

# Workaround to submodule update failure :
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - make sync
  - make

script: make test

notifications:
  email:
    on_success: change
    on_failure: always
