#
#
#==============================================================================

PRODUCT=hello

TARGETS=hello.phk helloa.phk

NO_FILTER=true

FILTER_SOURCE = $(SOURCE_DIR)

include ../make.vars
include ../make.common

#-----------------------------------------------------------------------------
