#
#==============================================================================

PRODUCT=Smarty

TARGETS = $(PRODUCT).phk

FILTER_SOURCE = $(SOURCE_DIR)/libs

KIT_NAME=Smarty_phk_building_kit

include ./make.vars
include ../make.common

#-----------------------------------------------------------------------------
