#
# Zend Framework
#
#==============================================================================

SUBDIRS = lib doc

KIT_NAME=zfw_phk_building_kit

include ./make.vars
include ./make.subdir

#-----------------------------------------------------------------------------
