#
# Zend Framework - Library packages
#
#==============================================================================

PRODUCT=zfw_core

TARGETS = $(PRODUCT).phk

FILTER_SOURCE = $(SOURCE_DIR)/library

include ../../make.vars
include ../../../../make.common

#-----------------------------------------------------------------------------
