#
#==============================================================================

PRODUCT=PHPUnit

TARGETS = $(PRODUCT).phk

FILTER_SOURCE = $(SOURCE_DIR)/PHPUnit

KIT_NAME=PHPUnit_phk_building_kit

include ./make.vars
include ../../make.common

#-----------------------------------------------------------------------------
