
SUBDIRS = hello mini getid3 zfw_doc

all: examples

include ../make.vars
include ../make.common

#-----------------------------

.PHONY: all examples clean

clean: clean_base

examples:
	@echo "Each example must be built and run from its subdirectory."

#-----------------------------------------------------------------------------
