#
# Zend Framework - Library packages
#
#==============================================================================

FILTER_SOURCE = $(SOURCE_DIR)/tests

include ../../../make.vars
include ../../../../../make.common

#-----------------------------------------------------------------------------
